### ISSUE TITLE
ECG recording stops without warning

### ISSUE THREAD

**Issue by lagj** [poml88/ecg-recorder-ios#2]
While “Save ECG stream” is active, a look back at the app often reveals that the recording has stopped. This can happen at various intervals (minutes to hours). No change in the location of the iPhone relative to the H10. There is usually a device error displayed (such as “gattDisconnected”). Could the app do either or both of: Send a notification or automatically attempt to restart the recording?

**Comment by poml88** [comment]
This is an interesting thought. Since I do not experience these disconnects I did not think about this. It should record basically forever, until memory is full or battery is empty. I tried this for 12 hours plus.
Can you tell me a bit more on your using environment, so I could maybe figure out what is wrong? What other error messages do you see than "gattDisconnected"?

Anyway, good point. Both possibly could be done on the "gattDisconnected" event. Which of the solutions would you prefer?
And I wonder which sort of notification should be displayed?

**Comment by TMcManus2018** [comment]
I've had a similar issue with a lost connection halting data collection on my Polar H10 using the EliteHRV app. They've told me that the app retries 3 times to reconnect following which they bring up a dialog box with an option to continue. The only problem is continuing just keeps recording in the same file so the time base is lost. A break in data collection of, say, an hour, looks in the data as if it never happened. I've suggested to them that any (significant) break in the data flow recording should result in a new timestamp.

As to my environment, it only happened once and that was in a overnight recording while in bed. Tossing and turning could have resulted in the H10 losing skin contact and stopping data transmission. You should be able to simulate this by simply removing the chest strap source in mid-recording and see what happens.

**Comment by lagj** [comment]
I’ve been paying more attention and the only error I ever see is gattDisconnected. I can’t tell why this is happening though. I’ve had long recordings over 12 hours, but sometimes get the error in a few minutes, and it can happen at any time. I like the suggestion of TMcManus2018 to partly borrow the behavior from EliteHRV, and as he suggests, always start a new file.

**Comment by poml88** [comment]
Hi, sorry for late reply, very busy times here. 
Thanks for the discussion, this is very useful. It seems that sometimes disconnects happen, but not for everyone. I do not understand why, maybe it has to do with H10 firmware version and/or iOS version and device, maybe wireless interference...
Anyway, as you pointed out, if the connection is lost the time base is lost. So a new file shall be started I think. 
I will have to look into if I can do something about this. I could try a restart in a new file, then also a notification that this has happened.
Maybe as a start I can try to get some notification in case the connection is lost. Then at least the user is aware of this.
Well, this is also not a high end ECG device, rather a sports pulse monitor... I am afraid about the connection stability only Polar can do something.
What would be your preferred first step for a new app version?

**Comment by TMcManus2018** [comment]
I suspect that it is caused by a loss of pulse to the H10 sensor. I happened to me during a long recording at night where motion (like rolling over) may have caused the H10 to cut off the connection.

Interestingly, when using the ECGRecorder app, I have to make sure to do a disconnect after a recording or other apps (like EliteHRV) cannot make a connection. It seems other apps must implicitly disconnect at the end of a session and then reconnect automatically when a new reading starts. They must us a different (automatic) protocol rather than the manual approach taken by ECGRecorder.

**Comment by TMcManus2018** [comment]
My preference would be for an automatic restart with a new time base in the file name when a connection is remade after being lost. There are probably lots of other considerations like how many connection retries (or how long) before just giving up.

**Comment by peter-kolenic** [comment]
Hi poml88, thank for the app.
I hit this problem twice, from 3 attempts to record (I started using the app 2 hours ago).
Have you considered restarting recording AND timestamping data at the same time ? We would end with one file to work with, with some no-data periods.
Another option would be to save data to disk every 1 minute, creating at least some data. I understand that as it is, all data is lost if disconnect occurs, right ?
Anyway, anything with at least some data would be great. Otherwise, I am afraid I won't end up with any data after my long biking sessions, as at least one disconnect every few hour seems to be expected.

**Comment by poml88** [comment]
That is weird. So, are you able to record any data at all? 
Do you remember what the error message was?
Normally, when the H10 gets disconnected, all data in memory should be saved. So no loss of data here. Unless the app is being closed hard.
Which firmware version are you on, and which app version?
I can test again, if the "save at loss of connection" works properly.

**Comment by poml88** [comment]
Hi all, ok, so there is a new app version in review now. It supports the automatic re-connect.
So if the connection is lost, the app tries to re-connect to the same device. If this is successful and the ECG stream was recorded before the loss of connection, the stream is restartet with a new timestamp. When saved, the file will have to fitting timestamp to the data in the file name.

I hope this improves the situation with the disconnects.

I did not implement any notifications yet, because it involves asking the user for permission etc. Maybe at a later stage. But the app shows how many times it did automatically re-connect.
